### ISSUE TITLE
Admin Image thumbnails not displaying correctly

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#2] opened 2018-11-01 20:41 UTC
Admin / Maker / Select Maker (e.g. Cristian Maghiar) / Images tab
I've added several different types of image (jpg, pdf, png) but the thumbnail boxes only display a question mark (?)

**Comment by Cristialt** [comment] 2018-11-02 19:31
thumbs are not ready; I plan to make a duplicate of the original image for this use

**Comment by Cristialt** [comment] 2018-12-04 14:58
done

**Closed as completed** 2019-03-04 11:24 UTC
Labels: done
